name: prep_whole_read
description: |
  Split bam files into plus and minus strand bam files for MACS3 peak calling
  Also convert the bam file to bed format and calculate (normalised) coverage tracks in bedgraph format
keywords:
  - samtools
  - bedtools
  - macs3
  - coverage
  - fai
  - bam
modules:
  - nf-core/samtools/view
  - goodwright/linux/command
  - nf-core/bedtools/bamtobed
  - nf-core/bedtools/genomecov
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id:FUS_KO_BRD4_plus_R2, group:FUS_KO_BRD4_plus, replicate:2, single_end:true]
  - bam:
      type: file
      description: BAM file
      pattern: "*.bam"
  - fai:
      type: file
      description: FAI file
      pattern: "*.fai"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam_plus:
      type: file
      description: BAM file containing reads on the plus strand
      pattern: "*_plus.bam"
  - bam_minus:
      type: file
      description: BAM file containing reads on the minus strand
      pattern: "*_minus.bam"
  - bed:
      type: file
      description: Bedfile containing the crosslink depths at genomic positions
      pattern: "*.bed"
  - coverage:
      type: file
      description: The crosslinks bed file turned into a bedgraph coverage file.
      pattern: "*.bedgraph"
  - coverage_norm:
      type: file
      description: The crosslinks bed file turned into a bedgraph coverage file normalised against total count
      pattern: "*.bedgraph"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@chris-cheshire"
